### ISSUE TITLE
آموزش ویدیویی برای این پروژه

### ISSUE THREAD

**Issue by ehsandavari** [ErFUN-KH/go-grpc-http-rest-microservice#1]
سلام لطفا درصورت امکان برای این پروژه آموزش ویدیویی یا یک مقاله درست کنید ممنون

**Comment by ErFUN-KH** [comment]
سلام وقت بخیر، از [اینجا](https://virgool.io/golangpub/%D8%B3%D8%A7%D8%AE%D8%AA-%D9%BE%D8%B1%D9%88%DA%98%D9%87-%D8%A8%D8%A7-%D9%85%D8%B9%D9%85%D8%A7%D8%B1%DB%8C-%D9%85%D8%A7%DB%8C%DA%A9%D8%B1%D9%88%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%D8%B2%D8%A8%D8%A7%D9%86-%DA%AF%D9%88%D9%84%D9%86%DA%AF-%D8%A7%D9%86%D8%AF%D9%BE%D9%88%DB%8C%D9%86%D8%AA-%D8%B1%D8%B3%D8%AA-%DA%A9%D9%88%D8%A8%D8%B1%D9%86%D8%AA%DB%8C-%D9%88-nyamxgxsuvqu) میتونید توی ۳ قسمت کامل بخونیدش
